makeCacheMatrix <- function(x = matrix()) {
  inv <- NULL   #setting the cache to Null
  set <- function(y) {  #set allows to reset the cache and use a different matrix
    x <<- y
    inv <<- NULL
  }
  get <- function() x  #get will return the matrix from the matrixobject
  setmat <- function(solve) inv <<- solve  #will calculate the inverse and write it back inv in  the parent environment 
  getmat <- function() inv  #will return the inv
  list(set = set, get = get, #makes the functions available by using a named list
       setmat = setmat,
       getmat = getmat)
}

cacheSolve <- function(x, ...) {#used to calculate the inv and fill the cache for a matix object generated by makeCacheMatrix
  inv <- x$getmat() #getting the current inv value from the cache
  if(!is.null(inv)) {  #checking if the value exists
    message("getting cached data")
    return(inv) #if it exists return the value
  }
  data <- x$get() #if not, calculating the inv, writing it in the cache and returning it
  inv <- solve(data, ...)
  x$setmat(inv)
  inv
}